name: SDK Compliance Tests

permissions:
  contents: read
  packages: read
  pull-requests: write

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  compliance:
    name: PostHog SDK compliance tests
    uses: PostHog/posthog-sdk-test-harness/.github/workflows/test-sdk-action.yml@6d19abb9c81e2262dacbe340e7dddda9c871c178
    with:
      adapter-dockerfile: "sdk_compliance_adapter/Dockerfile"
      adapter-context: "."
      test-harness-version: "0.10.0"
